name: App (CI)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/client/**'

jobs:
  App_CI:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src/client

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: src/client/package-lock.json

    - name: NPM Install
      run: npm ci

    - name: NPM Build
      run: npm run build --if-present

    - name: NPM Test
      run: npm test
