name: App (CI)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/client/**'

jobs:
  App_CI:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src/client

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: src/client/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
