name: Shared Infrastructure (CICD)

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**/shared-infrastructure-*.yml'
      - 'src/shared_infrastructure/**'

permissions:
  id-token: write
  contents: read

jobs:
  plan_prod:
    uses: ./.github/workflows/shared-infrastructure-plan.yml
    secrets: inherit
  apply_prod:
    needs: plan_prod
    uses: ./.github/workflows/shared-infrastructure-apply.yml
    secrets: inherit
