name: Shared Infra (CI)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/shared_infrastructure/**'

jobs:
  shared_infra_ci:
    name: Shared Infra (CI)
    runs-on: ubuntu-latest
     
    defaults:
      run:
        working-directory: src/shared_infrastructure

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v3
    - run: terraform init
    - run: terraform validate
    - run: terraform fmt --recursive
    - run: terraform plan
